### ISSUE TITLE
Unread post count should update in the title tag for us and for stations

### ISSUE THREAD

**Issue by alykat** [nprapps/liveblog-standalone#11] opened 2019-12-22 04:31 UTC
In the current/old liveblog, when new posts are published, the number of new posts is reflected in the title tag of the parent page — both on NPR.org and on stations. It would be great to port this over to the new liveblog.

May need to adapt the special pym liveblog loader:
https://github.com/nprapps/npr-pym-liveblog-loader

**Comment by thomaswilburn** [comment] 2019-12-22 04:33
Duplicate of #10

**Closed as completed by thomaswilburn** 2019-12-22 04:33 UTC
